### ISSUE TITLE
How define the positions of sources and probes arbitrary? 

### ISSUE THREAD

**Issue by BENYSU** [andre-batista/eispy2d#2]
Hi 
This is very interesting research and it can be generalize many research area. But how can we easily define the the positions of sources and probes arbitrary and not shown in your example.
 Thank you very much.
![cfg](https://user-images.githubusercontent.com/103613617/215324027-4ec63a4d-3235-4749-9478-a154fe168b7b.jpg)

**Comment by andre-batista** [comment]
Hi BENYSU!

Thanks for your message!

By default, the sources and probes are positioned in a circular fashion. Therefore, the scope of the library presupposes this arrangement around the image domain. To change the arrangement, as you demonstrated in your figure, is necessary to change the codes. If you change the function "get_coordinates_sdomain" in the "configuration.py" module, then you will be able to change the model, i.e., the arrangement of the probes and sources. But you are going to need to pay attention on the arguments, if you change them. Because this function is used in other modules, specially "richmond.py" where the Green function computation takes place.

Let me know

**Comment by andre-batista** [comment]
Hi BENYSU!

Thanks for your message!

By default, the sources and probes are positioned in a circular fashion. Therefore, the scope of the library presupposes this arrangement around the image domain. To change the arrangement, as you demonstrated in your figure, is necessary to change the codes. If you change the function "get_coordinates_sdomain" in the "configuration.py" module, then you will be able to change the model, i.e., the arrangement of the probes and sources. But you are going to need to pay attention on the arguments, if you change them. Because this function is used in other modules, specially "richmond.py" where the Green function computation takes place.

Let me know if you have more questions.

**Comment by andre-batista** [comment]
Hi BENYSU!

Thanks for your message!

By default, the sources and probes are positioned in a circular fashion.
Therefore, the scope of the library presupposes this arrangement around the
image domain. To change the arrangement, as you demonstrated in your
figure, is necessary to change the codes. If you change the function
"get_coordinates_sdomain" in the "configuration.py" module, then you will
be able to change the model, i.e., the arrangement of the probes and
sources. But you are going to need to pay attention on the arguments, if
you change them. Because this function is used in other modules, specially
"richmond.py" where the Green function computation takes place.

Let me know if you have more questions.
